#! /bin/bash

CONTAINER_NAME=${CONTAINER_NAME:-sentrifarm-grafana-dashboard}
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
#if [ -d "./logs" ];then
#	rm -fr ./logs/*
#fi

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 9980:80 -p 9981:81 -p 8125:8125/udp -p 8126:8126 -p 2003:2003/udp --name $CONTAINER_NAME pastcompute/grafana_graphite
